### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by gitihobo** [gaomingqi/Track-Anything#96]
Initializing BaseSegmenter to cuda:3
Traceback (most recent call last): File “G:.…\app.py”, line 385, in model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
File “G:.…\track_anything.py”, line 18, in init self.samcontroler = SamControler(self.sam_checkpoint, args.sam_model_type, args.device)
File “G:.…\interact_tools.py”, line 37, in init self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device) File “G:.…\base_segmenter.py”, line 26, in init self.model.to(device=self.device)
File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 1145, in to return self._apply(convert) File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 797, in _apply module._apply(fn)
File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 797, in _apply module._apply(fn) File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 797, in _apply module._apply(fn)
File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 820, in _apply param_applied = fn(param)
File “C:.…\Python310\lib\site-packages\torch\nn\modules\module.py”, line 1143, in convert return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

RuntimeError: CUDA error: invalid device ordinal CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by gitihobo** [comment]
This happens after python app.py

**Comment by JaneYang07** [comment]
I encountered the same error and fixed it by changing line 379 "args.device = 'cuda:3'" to "args.device = 'cuda:0'", as I only have a single GPU setup. I assumed the authors had multiple GPUs and they were running it on the fourth GPU.

**Comment by jorgevasquezp** [comment]
Sorry for re-hashing this. but shouldn't the cuda:N argument in app.py, be set when running the app with an argunment, as stated in readme in the Getting started section: Track-Anything gradio demo.
`# python app.py --device **cuda:0** --sam_model_type vit_b # for lower memory usage`

**Comment by gitihobo** [comment]
Makes sense
